# Frontend - Streamlit
FROM python:3.10-slim

WORKDIR /app

COPY . /app

RUN pip install --no-cache-dir streamlit socketio-client

EXPOSE 8501

CMD ["streamlit", "run", "client.py", "--server.port=8501", "--server.address=0.0.0.0"]
