version: '3.9'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"  # Ollama default port
    volumes:
      - ollama-data:/root/.ollama
    restart: unless-stopped
    networks:
      - chatbot-net
    tty: true

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - ollama
    networks:
      - chatbot-net

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    networks:
      - chatbot-net

networks:
  chatbot-net:
    driver: bridge

volumes:
  ollama-data:
